### ISSUE TITLE
关于数据集的疑问

### ISSUE THREAD

**Issue by Season-Chan** [jianweiguo/SpecularityNet-PSD#5]
感谢作者的分享！文章中的 highlight segmentation image T是通过对高光图像和非高光图像的运算得到的，运算里面涉及到的参数  ，即mask = 0.3*delta[0]+0.59*delta[1]+0.11*delta[2]中的0.3、0.59和0.11是经验值还是通过某个算法求的呢？

**Comment by zcq15** [comment]
> 感谢作者的分享！文章中的 highlight segmentation image T是通过对高光图像和非高光图像的运算得到的，运算里面涉及到的参数 ，即mask = 0.3_delta[0]+0.59_delta[1]+0.11*delta[2]中的0.3、0.59和0.11是经验值还是通过某个算法求的呢？

是RGB转灰度时各个色彩通道的权重
